"""Initial migration.

Revision ID: 6b698df7d618
Revises: 
Create Date: 2021-10-10 21:33:00.904505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b698df7d618'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver', sa.String(length=100), nullable=True),
    sa.Column('series', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
